language: ruby
rvm:
 - 2.3.1

variables:
  RSPEC_RETRY_RETRY_COUNT: "7"

# before_script:
#   - ruby -v
#   - which ruby
#   - touch log/application.log
#   - touch log/test.log
#   - bin/rails db:environment:set RAILS_ENV=test
#   - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load db:migrate

before_script:
  - psql -c "CREATE DATABASE erltest;" -U postgres
  - psql -c "CREATE USER rock_and_roll WITH PASSWORD 'rock_and_roll';" -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rspec
  # - bundle exec rake rubocop
  # - bundle exec rake brakeman

notifications:
  slack: schwaughlin:crRxhS7awljHvIl8quLRz4FA

addons:
  code_climate:
    repo_token: 
