language: ruby
rvm:
 - 2.3.1

before_script:
  - psql -c "CREATE DATABASE erltest;" -U postgres
  - psql -c "CREATE USER rock_and_roll WITH PASSWORD 'rock_and_roll';" -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rspec

notifications:
  slack: schwaughlin:crRxhS7awljHvIl8quLRz4FA

addons:
    code_climate:
        repo_token: df0356c1e55cd96ff1ad09d507b5cecc129deae5caf275a0d54a9ebc39bef44d

after_success:
  - coveralls
