defaults: &defaults
  adapter: postgresql
  username: nickschwaderer
  password: my_generic_pass_Password@01
  encoding: utf8
  host: localhost

development:
  database: erldev
  <<: *defaults

test: &test
  database: erltest
  <<: *defaults
